version: 0.1

phases:
  install:
    commands:
      - echo installing curl
      - apt-get update
      - apt-get install -y curl
      - echo Installing Yarn ....
      - /bin/bash --version
      - bash --version
      - echo $PATH
      - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
  pre_build:
    commands:
      - echo Installing dependencies
      - yarn
      - yarn test
  build:
    commands:
      - echo Building project...
      - yarn build
  post_build:
    commands:
      - echo completed build!
      - docker build -t sample/image .
